export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const LOG_OUT= 'LOG_OUT';
export const UPDATING_START = "UPDATING_START";
export const UPDATING_SUCCESS = "UPDATING_SUCCESS";
export const UPDATING_FAIL = "UPDATING_FAIL";
export const FOLLOW_USER = "FOLLOW_USER";
export const UN_FOLLOW_USER = "UN_FOLLOW_USER";

export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";

export const RETRIEVING_START = "RETRIEVING_START";
export const RETRIEVING_SUCCESS = "RETRIEVING_SUCCESS";
export const RETRIEVING_FAIL = "RETRIEVING_FAIL";


export const COMMENTING_START = "COMMENTING_START";
export const COMMENTING_SUCCESS = "COMMENTING_SUCCESS";
export const COMMENTING_FAIL = "COMMENTING_FAIL";


